-- TC_GB_04
-- By: Miguel Angel Lopez
-- Date: 2023-11-14
-- Description: Create a sequence to autogenerate userid
CREATE SEQUENCE APP_M_PROV_SELECC.USER_SECUENCE INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999 NOCYCLE CACHE 20 NOORDER;