-- TC_GB_04
-- By: Miguel Angel Lopez
-- Date: 2023-11-14
-- Description: All the references in the contract table
-- APP_M_PROV_SELECC.CONTRACT foreign keys

ALTER TABLE "APP_M_PROV_SELECC"."CONTRACT" ADD CONSTRAINT "CONTRACT_SUPPLIER_FK" FOREIGN KEY ("SUPPLIERID")
	  REFERENCES "APP_M_PROV_SELECC"."SUPPLIER" ("SUPPLIERID") ENABLE;
  ALTER TABLE "APP_M_PROV_SELECC"."CONTRACT" ADD CONSTRAINT "CONTRACTS_PRODUCT_FK" FOREIGN KEY ("PRODUCTID")
	  REFERENCES "APP_M_PROV_SELECC"."PRODUCT" ("PRODUCTID") ENABLE;