-- TC_GB_04
-- By: Miguel Angel Lopez
-- Date: 2023-11-14
-- Description: All the references in the product table
-- APP_M_PROV_SELECC.PRODUCT foreign keys

ALTER TABLE "APP_M_PROV_SELECC"."PRODUCT" ADD CONSTRAINT "PRODUCT_SELECTIONACTIVITY_FK" FOREIGN KEY ("ACTIVITYID")
	  REFERENCES "APP_M_PROV_SELECC"."SELECTIONACTIVITY" ("ACTIVITYID") ENABLE;
  ALTER TABLE "APP_M_PROV_SELECC"."PRODUCT" ADD CONSTRAINT "PRODUCT_SELECTIONCRITERIA_FK" FOREIGN KEY ("SELECTIONCRITERIAID")
	  REFERENCES "APP_M_PROV_SELECC"."SELECTIONCRITERIA" ("SELECTIONCRITERIAID") ENABLE;
  ALTER TABLE "APP_M_PROV_SELECC"."PRODUCT" ADD CONSTRAINT "FKO54S4MMRAS7348ND8H0E1JBCM" FOREIGN KEY ("ACTIVITYNAME")
	  REFERENCES "APP_M_PROV_SELECC"."SELECTIONACTIVITY" ("ACTIVITYID") ENABLE;