-- TC_GB_04
-- By: Miguel Angel Lopez
-- Date: 2023-11-14
-- Description: All the references in the SUPPLIERPRODUCTV1 table
-- APP_M_PROV_SELECC.SUPPLIERPRODUCTV1 foreign keys

ALTER TABLE "APP_M_PROV_SELECC"."SUPPLIERPRODUCTV1" ADD CONSTRAINT "FK8TCN4HP5MGB1ONQXH1XC66JWY" FOREIGN KEY ("SUPPLIERID")
	  REFERENCES "APP_M_PROV_SELECC"."SUPPLIER" ("SUPPLIERID") ENABLE;
  ALTER TABLE "APP_M_PROV_SELECC"."SUPPLIERPRODUCTV1" ADD CONSTRAINT "FKJ936J46Y4LF9BEQUL4GRYCTKA" FOREIGN KEY ("PRODUCTID")
	  REFERENCES "APP_M_PROV_SELECC"."PRODUCT" ("PRODUCTID") ENABLE;