-- TC_GB_04
-- By: Miguel Angel Lopez
-- Date: 2023-11-14
-- Description: All the references in the SELECTIONACTIVITY table
-- APP_M_PROV_SELECC.SELECTIONACTIVITY foreign keys

ALTER TABLE "APP_M_PROV_SELECC"."SELECTIONACTIVITY" ADD CONSTRAINT "FK_RESPONSIBLEAREA" FOREIGN KEY ("RESPONSIBLEAREAID")
	  REFERENCES "APP_M_PROV_SELECC"."RESPONSIBLEAREA" ("RESPONSIBLEAREAID") ENABLE;