-- TC_GB_04
-- By: Miguel Angel Lopez
-- Date: 2023-11-14
-- Description: creates index for colum userid
-- APP_M_PROV_SELECC

CREATE UNIQUE INDEX "APP_M_PROV_SELECC"."SYS_C008514" ON "APP_M_PROV_SELECC"."USERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;